/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSiteStatusRouteImport } from './routes/api/site-status'
import { Route as ApiReconstructionExamplesRouteImport } from './routes/api/reconstruction-examples'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGeneratePdfRouteImport } from './routes/api/generate-pdf'
import { Route as ApiGenerateMaterialRouteImport } from './routes/api/generate-material'
import { Route as ApiGenerateLeafletRouteImport } from './routes/api/generate-leaflet'
import { Route as ApiCalculateRenovationRouteImport } from './routes/api/calculate-renovation'
import { Route as ApiBuildingInfoRouteImport } from './routes/api/building-info'
import { Route as ApiAdvisorRouteImport } from './routes/api/advisor'
import { Route as ApiAddressSearchRouteImport } from './routes/api/address-search'

const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteStatusRoute = ApiSiteStatusRouteImport.update({
  id: '/api/site-status',
  path: '/api/site-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReconstructionExamplesRoute =
  ApiReconstructionExamplesRouteImport.update({
    id: '/api/reconstruction-examples',
    path: '/api/reconstruction-examples',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePdfRoute = ApiGeneratePdfRouteImport.update({
  id: '/api/generate-pdf',
  path: '/api/generate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateMaterialRoute = ApiGenerateMaterialRouteImport.update({
  id: '/api/generate-material',
  path: '/api/generate-material',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateLeafletRoute = ApiGenerateLeafletRouteImport.update({
  id: '/api/generate-leaflet',
  path: '/api/generate-leaflet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalculateRenovationRoute = ApiCalculateRenovationRouteImport.update({
  id: '/api/calculate-renovation',
  path: '/api/calculate-renovation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildingInfoRoute = ApiBuildingInfoRouteImport.update({
  id: '/api/building-info',
  path: '/api/building-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvisorRoute = ApiAdvisorRouteImport.update({
  id: '/api/advisor',
  path: '/api/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddressSearchRoute = ApiAddressSearchRouteImport.update({
  id: '/api/address-search',
  path: '/api/address-search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/manifesto': typeof ManifestoRoute
  '/api/address-search': typeof ApiAddressSearchRoute
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/building-info': typeof ApiBuildingInfoRoute
  '/api/calculate-renovation': typeof ApiCalculateRenovationRoute
  '/api/generate-leaflet': typeof ApiGenerateLeafletRoute
  '/api/generate-material': typeof ApiGenerateMaterialRoute
  '/api/generate-pdf': typeof ApiGeneratePdfRoute
  '/api/health': typeof ApiHealthRoute
  '/api/reconstruction-examples': typeof ApiReconstructionExamplesRoute
  '/api/site-status': typeof ApiSiteStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/manifesto': typeof ManifestoRoute
  '/api/address-search': typeof ApiAddressSearchRoute
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/building-info': typeof ApiBuildingInfoRoute
  '/api/calculate-renovation': typeof ApiCalculateRenovationRoute
  '/api/generate-leaflet': typeof ApiGenerateLeafletRoute
  '/api/generate-material': typeof ApiGenerateMaterialRoute
  '/api/generate-pdf': typeof ApiGeneratePdfRoute
  '/api/health': typeof ApiHealthRoute
  '/api/reconstruction-examples': typeof ApiReconstructionExamplesRoute
  '/api/site-status': typeof ApiSiteStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/manifesto': typeof ManifestoRoute
  '/api/address-search': typeof ApiAddressSearchRoute
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/building-info': typeof ApiBuildingInfoRoute
  '/api/calculate-renovation': typeof ApiCalculateRenovationRoute
  '/api/generate-leaflet': typeof ApiGenerateLeafletRoute
  '/api/generate-material': typeof ApiGenerateMaterialRoute
  '/api/generate-pdf': typeof ApiGeneratePdfRoute
  '/api/health': typeof ApiHealthRoute
  '/api/reconstruction-examples': typeof ApiReconstructionExamplesRoute
  '/api/site-status': typeof ApiSiteStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/manifesto'
    | '/api/address-search'
    | '/api/advisor'
    | '/api/building-info'
    | '/api/calculate-renovation'
    | '/api/generate-leaflet'
    | '/api/generate-material'
    | '/api/generate-pdf'
    | '/api/health'
    | '/api/reconstruction-examples'
    | '/api/site-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/manifesto'
    | '/api/address-search'
    | '/api/advisor'
    | '/api/building-info'
    | '/api/calculate-renovation'
    | '/api/generate-leaflet'
    | '/api/generate-material'
    | '/api/generate-pdf'
    | '/api/health'
    | '/api/reconstruction-examples'
    | '/api/site-status'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/manifesto'
    | '/api/address-search'
    | '/api/advisor'
    | '/api/building-info'
    | '/api/calculate-renovation'
    | '/api/generate-leaflet'
    | '/api/generate-material'
    | '/api/generate-pdf'
    | '/api/health'
    | '/api/reconstruction-examples'
    | '/api/site-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ManifestoRoute: typeof ManifestoRoute
  ApiAddressSearchRoute: typeof ApiAddressSearchRoute
  ApiAdvisorRoute: typeof ApiAdvisorRoute
  ApiBuildingInfoRoute: typeof ApiBuildingInfoRoute
  ApiCalculateRenovationRoute: typeof ApiCalculateRenovationRoute
  ApiGenerateLeafletRoute: typeof ApiGenerateLeafletRoute
  ApiGenerateMaterialRoute: typeof ApiGenerateMaterialRoute
  ApiGeneratePdfRoute: typeof ApiGeneratePdfRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReconstructionExamplesRoute: typeof ApiReconstructionExamplesRoute
  ApiSiteStatusRoute: typeof ApiSiteStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-status': {
      id: '/api/site-status'
      path: '/api/site-status'
      fullPath: '/api/site-status'
      preLoaderRoute: typeof ApiSiteStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reconstruction-examples': {
      id: '/api/reconstruction-examples'
      path: '/api/reconstruction-examples'
      fullPath: '/api/reconstruction-examples'
      preLoaderRoute: typeof ApiReconstructionExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-pdf': {
      id: '/api/generate-pdf'
      path: '/api/generate-pdf'
      fullPath: '/api/generate-pdf'
      preLoaderRoute: typeof ApiGeneratePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-material': {
      id: '/api/generate-material'
      path: '/api/generate-material'
      fullPath: '/api/generate-material'
      preLoaderRoute: typeof ApiGenerateMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-leaflet': {
      id: '/api/generate-leaflet'
      path: '/api/generate-leaflet'
      fullPath: '/api/generate-leaflet'
      preLoaderRoute: typeof ApiGenerateLeafletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calculate-renovation': {
      id: '/api/calculate-renovation'
      path: '/api/calculate-renovation'
      fullPath: '/api/calculate-renovation'
      preLoaderRoute: typeof ApiCalculateRenovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/building-info': {
      id: '/api/building-info'
      path: '/api/building-info'
      fullPath: '/api/building-info'
      preLoaderRoute: typeof ApiBuildingInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advisor': {
      id: '/api/advisor'
      path: '/api/advisor'
      fullPath: '/api/advisor'
      preLoaderRoute: typeof ApiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/address-search': {
      id: '/api/address-search'
      path: '/api/address-search'
      fullPath: '/api/address-search'
      preLoaderRoute: typeof ApiAddressSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ManifestoRoute: ManifestoRoute,
  ApiAddressSearchRoute: ApiAddressSearchRoute,
  ApiAdvisorRoute: ApiAdvisorRoute,
  ApiBuildingInfoRoute: ApiBuildingInfoRoute,
  ApiCalculateRenovationRoute: ApiCalculateRenovationRoute,
  ApiGenerateLeafletRoute: ApiGenerateLeafletRoute,
  ApiGenerateMaterialRoute: ApiGenerateMaterialRoute,
  ApiGeneratePdfRoute: ApiGeneratePdfRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReconstructionExamplesRoute: ApiReconstructionExamplesRoute,
  ApiSiteStatusRoute: ApiSiteStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
