services:
  - type: web
    name: clean-renovuj
    runtime: node
    rootDir: clean_renovuj
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
